#import <Cocoa/Cocoa.h>

typedef enum {
    EVENT_CLOSE,

    EVENT_RESIZE,
    EVENT_MOVE,

    EVENT_FOCUS_GAINED,
    EVENT_FOCUS_LOST,

    EVENT_MOUSE_MOVE,
    EVENT_MOUSE_BUTTON,
    EVENT_MOUSE_SCROLL,

    EVENT_KEY_DOWN,
    EVENT_KEY_UP,
    EVENT_TEXT_INPUT,
} EventType;

typedef struct {
    EventType type;

    union {
        struct {
            uint32_t width;
            uint32_t height;
        } resize;

        struct {
            int32_t x;
            int32_t y;
        } move;

        struct {
            double x;
            double y;
        } mouse_move;

        struct {
            uint32_t button;
            bool pressed;
        } mouse_button;

        struct {
            double x;
            double y;
        } mouse_scroll;

        struct {
            uint32_t key_code;
            bool pressed;
            bool repeat;
        } key;

        struct {
            uint32_t codepoint;
        } text_input;
    } data;
} Event;

typedef struct {
    double x;
    double y;
    uint32_t width;
    uint32_t height;
    bool has_position;
} WindowCreateInfo;

void *applicationCreate(void) {
    NSApplication *app = [NSApplication sharedApplication];

    [app setActivationPolicy:NSApplicationActivationPolicyRegular];

    return (__bridge_retained void *)app;
}

void applicationDestroy(void *handle) {
    NSApplication *app = (__bridge_transfer NSApplication *)handle;

    [app terminate:nil];
}

bool applicationPollEvent(void *app_handle, Event *event) {
    NSApplication *app = (__bridge NSApplication *)app_handle;

    NSEvent *native_event = [app nextEventMatchingMask:NSEventMaskAny
                                             untilDate:[NSDate distantPast]
                                                inMode:NSDefaultRunLoopMode
                                               dequeue:YES];

    if (native_event == nil) {
        return false;
    }

    switch ([native_event type]) {
        case NSEventTypeKeyDown:
            event->type = EVENT_KEY_DOWN;
            event->data.key.key_code = [native_event keyCode];
            event->data.key.pressed = true;
            event->data.key.repeat = [native_event isARepeat];
            break;

        case NSEventTypeKeyUp:
            event->type = EVENT_KEY_UP;
            event->data.key.key_code = [native_event keyCode];
            event->data.key.pressed = false;
            event->data.key.repeat = false;
            break;

        case NSEventTypeFlagsChanged:
            // Modifier keys (shift, ctrl, alt, cmd)
            event->type = EVENT_KEY_DOWN;
            event->data.key.key_code = [native_event keyCode];
            event->data.key.pressed = true;
            event->data.key.repeat = false;
            break;

        case NSEventTypeMouseMoved:
        case NSEventTypeLeftMouseDragged:
        case NSEventTypeRightMouseDragged:
        case NSEventTypeOtherMouseDragged: {
            event->type = EVENT_MOUSE_MOVE;

            NSPoint pos = [native_event locationInWindow];
            event->data.mouse_move.x = pos.x;
            event->data.mouse_move.y = pos.y;

            break;
        }

        case NSEventTypeLeftMouseDown:
        case NSEventTypeRightMouseDown:
        case NSEventTypeOtherMouseDown:
            event->type = EVENT_MOUSE_BUTTON;
            event->data.mouse_button.button = [native_event buttonNumber];
            event->data.mouse_button.pressed = true;
            break;

        case NSEventTypeLeftMouseUp:
        case NSEventTypeRightMouseUp:
        case NSEventTypeOtherMouseUp:
            event->type = EVENT_MOUSE_BUTTON;
            event->data.mouse_button.button = [native_event buttonNumber];
            event->data.mouse_button.pressed = false;
            break;

        case NSEventTypeScrollWheel:
            event->type = EVENT_MOUSE_SCROLL;
            event->data.mouse_scroll.x = [native_event scrollingDeltaX];
            event->data.mouse_scroll.y = [native_event scrollingDeltaY];
            break;

        case NSEventTypeMouseEntered:
        case NSEventTypeMouseExited:
            // Optional: mouse enter/leave events
            break;

        case NSEventTypeApplicationDefined:
            // Custom events generated by your application
            break;

        default:
            [NSApp sendEvent:native_event];
            return false;
    }

    return true;
}

void *windowCreate(void *app_handle, WindowCreateInfo info) {
    NSApplication *app = (__bridge NSApplication *)app_handle;

    NSRect rect;

    if (info.has_position) {
        rect = NSMakeRect(
            info.x,
            info.y,
            info.width,
            info.height
        );
    } else {
        rect = NSMakeRect(
            0,
            0,
            info.width,
            info.height
        );
    }

    NSWindow *window = [[NSWindow alloc]
        initWithContentRect:rect
        styleMask:
            NSWindowStyleMaskTitled |
            NSWindowStyleMaskClosable |
            NSWindowStyleMaskResizable
        backing:NSBackingStoreBuffered
        defer:NO];

    if (!info.has_position) {
        [window center];
    }

    NSView *view = [window contentView];

    [view setWantsLayer:YES];

    CAMetalLayer *layer = [CAMetalLayer layer];
    [view setLayer:layer];

    CocoaWindow *out = malloc(sizeof(CocoaWindow));
    out->window = (__bridge_retained void *)window;
    out->view = (__bridge void *)view;
    out->metal_layer = (__bridge void *)layer;

    return out;
}

void windowDestroy(void *handle) {
    NSWindow *window = (__bridge_transfer NSWindow *)handle;
    [window close];
}

void *windowGetView(void *handle) {
    NSWindow *window = (__bridge NSWindow *)handle;
    return (__bridge void *)[window contentView];
}

void windowSetTitle(void *handle, const char *title) {
    NSWindow *window = (__bridge NSWindow *)handle;

    NSString *string = [NSString stringWithUTF8String:title];
    [window setTitle:string];
}
